# Site settings
title: Vincent Wong
email: vincetallica@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vincent Wong - engineer, entrepreneur, web dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vincetallica
github_username:  vincetallica
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
# Build settings
#markdown: kramdown
#theme: minima
#gems:#
  #- jekyll-feed
#exclude:#
  #- Gemfile
  #- Gemfile.lock
